[build]
builder = "python"

[deploy]
startCommand = "cd backend && pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
